config/routes.rb
Tvwc::Application.routes.draw do 
  resources :posts, :has_many => :comments

  resources :comments

  get ':controller/:action/:id'
  get':controller/:action/:id.:format'

  devise_for :users

  root :to => 'pages#home'
  get 'links'=>"pages#links"

  get 'stories' => "pages#stories"
  get "posts/show"
  get "posts/new"
  get "posts/index"

  get "comments/index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :title, :content, presence: true
  attr_accessible :body, :name, :post_id, :user_id, :post
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :posted, :title, :comments #, :post_id

  validates :title, :content, presence: true

  belongs_to :user
  validates :user_id, presence: true
            #:uniqueness => true
  has_many :comments #, :dependant => :destroy
  # has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_many :posts, :dependent => :destroy
  has_many :comments #:dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def links
  end

  def stories
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_user.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = current_user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :body %>
    <%= f.association :post %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="footer  fixed-bottom">
	<small> 
		TVWC Office Bearers private site built with Ruby on Rails by Louise Bally
	</small>
	</div>

app/views/layouts/_header.html.erb
	
	<div class="navbar navbar-inverse">
		<div class="navbar navbar-fixed-top">
	<div><%= image_tag("header_long.jpg", :alt => "tweed valley wildlife carers") %> 
</div>
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <!--Be user to leave the brand out there if you want it shown-->
             
             <%= link_to "TVWC Blog", root_path, class: "brand" %>

             <!-- everything that you want hidden at 940px or less, place within here -->
                <div class="nav-collapse">
                    <ul class="nav"> 
                        <li>
                            <%= link_to 'Topics',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'links',  links_path %>
                        </li>
                        <li>    
                            <%= link_to 'Stories',  stories_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                        <% if user_signed_in? %>
                                 <li><%= link_to 'Edit Profile',  edit_user_registration_path %></li>
                                <li><%= link_to 'Logout',  destroy_user_session_path, method: :delete %>
                                <% else %>
                                <li><%= link_to 'Login',  new_user_session_path %></li>
                                <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tvwc Private Site</title>
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<Div class="container">
		<% flash.each do |name, msg| %>
         	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
          <% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<h1>You are logged in </h1>
<% else %>
    <div class="row-fluid">
	  <div class="span4">
  	<div class="hero-unit">
  	Topics
  </div>
	</div>
  
  		<div class="span8 ">

  			<h1>Welcome to the TVWC Office Bearers in CyberSpace </h1>
	<p> If you have landed on this page it is by invitation only. The database already has your email address. If you are unable to sign up contact group webmaster.</p>
	<p>After signing up you will have access to the site content. All office bearers can create and read posts.</p>
	<p> 
	<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-success btn-large" %>
	</p>

</div>
<br/>
<br/><br/><br/><br/><br/><br/>


</div>
<% end %>



		
	

	

	
	

app/views/pages/links.html.erb
<h1>Useful links and phone numbers</h1>
<p>Find me in app/views/pages/links.html.erb</p>

app/views/pages/stories.erb
<h1>Stories</h1>
A place for posting stories about currenty animals or birds in care, interesting rescues or stories that can be used in newsletters or on the public website.


<h1>Guidelines for using the Office Bearers Site and other things for the index posts page</h1>


<p>Code of Conduct- to follow the code of conduct already in place for the group.</p>
<p>Instructions for posting to the blog</p>
<p>Privacy Policy</p>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :title, as: :text, input_html: { rows: "3" } %>
    <%= f.input :content %>
    <%= f.input :posted %>
  
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="span9">
<tr>
    <td width="25%"><strong><%= post.title %></strong></td>
  <td width="60%"> <%= post.content %></td>
<td width="15%"><%= post.posted %></td>
    <tr><td><%= link_to 'Show', post %></td>
    	<% if current_user == post.user %>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</tr>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table class="table table-striped">
  <thead>
    <th></th>
    <th></th>
    <th></th>
  </thead>
    <tbody>
      <%= render @posts %>
    </tbody>
</table>
<br />
<%= link_to 'New Post', new_post_path %>

  

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
	<div class="span6 offset3">
	<div class="well">
			  	<p>
		<%= @post.title %>
				 	</p>
				 	<p>
		<%= @post.content %>
           </p>	
           <p> 	  
    <%= @post.user.name %>
					 </p>
					 <p>
	 <%= @post.posted %>
				  </p>
					 
		<%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Back', posts_path %>
		<%= link_to 'reply', new_comment_path %>
		 	
	   </div>
   </div>
 </div>